<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
    <Configuration>Release</Configuration>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <PropertyGroup>
    <Company>DJLang</Company>
    <Copyright>Copyright @ DJ 2024</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ROPlugin\RaidOverhaul.csproj" />
    <ProjectReference Include="..\ROPrepatch\LegionPrePatch.csproj" />
    <ProjectReference Include="..\ROPackets\RaidOverhaulFika.csproj" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="pwsh -NoProfile -ExecutionPolicy Bypass ../build.ps1" WorkingDirectory="$(ProjectDir)" />
  </Target>

</Project>