<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
    <AssemblyName>LegionPrePatch</AssemblyName>
    <Description>PrePatch for the Legion Boss from Raid Overhaul</Description>
    <Version>2.6.1</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>
  
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>
  
  <ItemGroup>
		<Reference Include="spt-common">
		  <HintPath>..\..\..\..\BepInEx\plugins\spt\spt-common.dll</HintPath>
		</Reference>
    <Reference Include="0Harmony">
      <HintPath>..\..\..\..\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>..\..\..\..\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>..\..\..\..\BepInEx\core\Mono.Cecil.dll</HintPath>
    </Reference>
		<Reference Include="Newtonsoft.Json">
		  <HintPath>..\..\..\Managed\Newtonsoft.Json.dll</HintPath>
		</Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\..\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>