<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
    <AssemblyName>RaidOverhaul</AssemblyName>
    <Description>A large overhaul for raids including events and dead body clean up.</Description>
    <Version>2.6.1</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
	<Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ROPrepatch\LegionPrePatch.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Reference Include="0Harmony">
		  <HintPath>..\..\..\..\BepInEx\core\0Harmony.dll</HintPath>
		</Reference>
		<Reference Include="spt-custom">
		  <HintPath>..\..\..\..\BepInEx\plugins\spt\spt-custom.dll</HintPath>
		</Reference>
		<Reference Include="spt-singleplayer">
		  <HintPath>..\..\..\..\BepInEx\plugins\spt\spt-singleplayer.dll</HintPath>
		</Reference>
		<Reference Include="spt-common">
		  <HintPath>..\..\..\..\BepInEx\plugins\spt\spt-common.dll</HintPath>
		</Reference>
		<Reference Include="spt-reflection">
		  <HintPath>..\..\..\..\BepInEx\plugins\spt\spt-reflection.dll</HintPath>
		</Reference>
		<Reference Include="AnimationSystem.Types">
		  <HintPath>..\..\..\Managed\AnimationSystem.Types.dll</HintPath>
		</Reference>
		<Reference Include="Assembly-CSharp">
 		  <HintPath>..\..\..\Managed\Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="BepInEx">
		  <HintPath>..\..\..\..\BepInEx\core\BepInEx.dll</HintPath>
		</Reference>
		<Reference Include="bsg.console.core">
		  <HintPath>..\..\..\Managed\bsg.console.core.dll</HintPath>
		</Reference>
		<Reference Include="Comfort">
		  <HintPath>..\..\..\Managed\Comfort.dll</HintPath>
		</Reference>
		<Reference Include="Comfort.Unity">
		  <HintPath>..\..\..\Managed\Comfort.Unity.dll</HintPath>
		</Reference>
		<Reference Include="DissonanceVoip">
		  <HintPath>..\..\..\Managed\DissonanceVoip.dll</HintPath>
		</Reference>
		<Reference Include="ItemComponent.Types">
		  <HintPath>..\..\..\Managed\ItemComponent.Types.dll</HintPath>
		</Reference>
		<Reference Include="Newtonsoft.Json">
		  <HintPath>..\..\..\Managed\Newtonsoft.Json.dll</HintPath>
		</Reference>
		<Reference Include="Sirenix.Serialization">
		  <HintPath>..\..\..\Managed\Sirenix.Serialization.dll</HintPath>
		</Reference>
		<Reference Include="Unity.TextMeshPro">
		  <HintPath>..\..\..\Managed\Unity.TextMeshPro.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine">
		  <HintPath>..\..\..\Managed\UnityEngine.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AnimationModule">
		  <HintPath>..\..\..\Managed\UnityEngine.AnimationModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AssetBundleModule">
		  <HintPath>..\..\..\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AudioModule">
		  <HintPath>..\..\..\Managed\UnityEngine.AudioModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
		  <HintPath>..\..\..\Managed\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.IMGUIModule">
		  <HintPath>..\..\..\Managed\UnityEngine.IMGUIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputLegacyModule">
		  <HintPath>..\..\..\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextRenderingModule">
		  <HintPath>..\..\..\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UI">
		  <HintPath>..\..\..\Managed\UnityEngine.UI.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>